### ISSUE TITLE
paths.d doesn't exist when macOS 10.12 is installed fresh

### ISSUE THREAD

**Issue by rspeed** [mono/bockbuild#37]
One odd change – possibly a bug – in Sierra is that the directory `/etc/paths.d` doesn't exist in clean installs of macOS Sierra. As a result, the postinstall script of the Mono installer package is unable to add mono to $PATH. Regardless of whether the upstream of this is a bug or an intended change, it's easy enough to work around by adding `mkdir -p /etc/paths.d` to the postinstall script.

See also: dotnet/core-setup#362

**Comment by akoeplinger** [comment]
This was fixed in the Mono 4.6.1 release.
